# Generated by Django 5.0.6 on 2024-07-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_category_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller')], on_delete=django.db.models.deletion.CASCADE, to='movies.category'),
        ),
    ]
