# Generated by Django 5.0.6 on 2024-07-03 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('science_fiction', 'Science Fiction'), ('action', 'Action')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.category'),
        ),
    ]
