# Generated by Django 5.0.6 on 2024-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_category_name_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Science Fiction', 'Science Fiction'), ('ASction', 'Action')], max_length=100),
        ),
    ]
